image: docker:latest

variables:
  APP: xmas2022-service # ECR container
  LABEL: spin # LABEL=subdomain
  ARGOCD_PATH_SERVICE: services/spin2022

services:
  - docker:dind

stages:
  - build
  - deploy-tag

before_script:
  - docker info
  - which aws || apk add --no-cache curl jq python3 py-pip
  - which aws || pip install awscli

include:
- project: infrastructure/gitlab-cicd
  file: ci-Build.gitlab-ci.yml
  ref: master
- project: infrastructure/gitlab-cicd
  file: cd-Deploy-Tag.gitlab-ci.yml
  ref: master
